---
version: '2.2'
services:
  rump:
    init: true
    build:
      context: ./
      dockerfile: infra/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      # cache dependencies
      - deps:/go/pkg/mod
  redis:
    init: true
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
volumes:
  deps:
    driver: local
